/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bowling_game_kata

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class BowlingGameTest {
    @Test
    fun testGutterGame() {
        val game = Game()
        for (i in 1..20) {
            game.roll(0)
        }
        assertEquals(0, game.score())
    }
}
