/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bowling_game_kata

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class BowlingGameTest {
    @Test
    fun testGutterGame() {
        val game = Game()
        rollMany(game, 20, 0)
        assertEquals(0, game.score())
    }

    @Test
    fun testAllOnes() {
        val game = Game()
        rollMany(game, 20, 1)
        assertEquals(20, game.score())
    }

//    @Test
//    fun testOneSpare() {
//        val game = Game()
//        game.roll(5)
//        game.roll(5) // makes the spare
//        game.roll(3) // adds bonus
//        rollMany(game, 17, 0)
//        assertEquals(16, game.score())
//    }

    fun rollMany(game: Game, rolls: Int, pins: Int) {
        for (i in 1..rolls) {
            game.roll(pins)
        }
    }
}
